Manage expenses + workflow
gaschneider/expenses_management pull request #5
Opened 2024-12-21 23:05 UTC by gaschneider

This is the PR that brings the entire system together, giving access to the expenses page, and running the workflow to track approvals and rejections.

Still missing the tests, will add it soon

2024-12-24 22:52 UTC, magicblak requested changes
1. Form validation: The expense form lacks front-end validation, allowing submission with empty values.
2. Comment persistence: Comments added during status transitions are not being saved in the database.
3. Table sorting: The table sorting functionality is not working correctly.

Aside from these issues, the rest of the workflow and expense registration is working as expected.

2024-12-27 19:52 UTC, gaschneider commented
> 1. Form validation: The expense form lacks front-end validation, allowing submission with empty values.
> 2. Comment persistence: Comments added during status transitions are not being saved in the database.
> 3. Table sorting: The table sorting functionality is not working correctly.
> 
> Aside from these issues, the rest of the workflow and expense registration is working as expected.

Addressed the issues above, also made Currency a single value enum for now, since we still need to address the currency in rules, issue #6 created for it

2024-12-31 05:54 UTC, magicblak reviewed
1. Users without permission to create expenses can still view the buttom to create.
2. Departments dropdown lists all departments, including those the user lacks permission to view (dropdown only, not data).
3. VIEW_EXPENSES permission grants access to the expenses page but doesn't display the list. APPROVE_EXPENSES is incorrectly required to view expenses

2024-12-31 06:57 UTC, gaschneider commented
Addressed the issues mentioned, should be working now.

2025-01-02 23:59 UTC, magicblak reviewed
Department dropdown list in expenses page is not listing all departments to admin

2025-01-03 03:54 UTC, gaschneider commented
> Department dropdown list in expenses page is not listing all departments to admin

Addressed issue

2025-01-04 00:38 UTC, magicblak approved these changes

2025-01-04 01:42 UTC, merged