Data viz
gaschneider/expenses_management pull request #7
Opened 2024-12-31 05:29 UTC by magicblak

This pull request integrates an interactive Data Visualization (Dataviz) component and enhances the expense management module with comprehensive updates to functionality, permissions, and user interface.

2025-01-11 02:48 UTC, gaschneider requested changes
Need to clean up some unused stuff, fix some patterns, improve typification, also colors in charts don't seem to show up, not sure if it is supposed to be same color all.

Some tests would be also valuable to be added, at least to validate permissions and endpoints value check.

2025-01-11 02:48 UTC, gaschneider commented on client/src/pages/DataAnalysis/components/DataAnalysisDatePicker.tsx
> +export const DataAnalysisDatePicker: React.FC<{
Did you check the other date picker ? it can probably reused, just move to a shared/components folder and use in both pages, expense and data analysis

2025-01-11 02:48 UTC, gaschneider commented on client/src/pages/DataAnalysis/DataAnalysPage.tsx
> +  const [totalAmountPerStatus, setTotalAmountPerStatus] = useState([]);
These states don't seem to be used in here, any reason to keep them ?

2025-01-11 02:48 UTC, gaschneider commented on client/src/pages/DataAnalysis/DataAnalysPage.tsx
> +import api from "../../api/axios.config";
unused import, some clean up is needed in unused imports/variables

2025-01-11 02:48 UTC, gaschneider commented on client/src/pages/DataAnalysis/hooks/useDataAnalysis.ts
> +  percentageCountPerStatus: [];
Proper types needed in here

2025-01-11 02:48 UTC, gaschneider commented on client/src/pages/DataAnalysis/hooks/useDataAnalysis.ts
> +  const fetchSummary = useCallback(async (params: any = {}) => {
Proper types for params in these fetch functions as well

2025-01-11 02:48 UTC, gaschneider commented on client/src/pages/DataAnalysis/hooks/useDataAnalysis.ts
> +      const response = await api.get("/dataAnalysis/statuses_count", {
Better to follow a single pattern for the endpoint names, either `dataAnalysis/statuses-count` or `dataAnalysis/statuses_count`, personally I would go with the first, since other stuff are already like that

2025-01-11 02:48 UTC, gaschneider commented on client/src/pages/DataAnalysis/hooks/useExpenseDepartments.ts
> +export const useExpenseDepartments = () => {
This should be named properly since it is related to the data analysis departments. File and variables are named after expenses instead.

2025-01-11 02:48 UTC, gaschneider commented on client/src/pages/ExpensesPage.tsx
> +import { useState, useEffect, useMemo } from "react";
This file doesn't seem to be used, probably can delete ?

2025-01-11 02:48 UTC, gaschneider commented on client/src/components/Layout.tsx
>    }, [
Missing dependency in hook

2025-01-11 02:48 UTC, gaschneider commented on server/src/index.ts
> +      //await sequelize.sync({ alter: true }); // Be careful with this in production!
This should be uncommented

2025-01-11 02:48 UTC, gaschneider commented on server/src/controllers/dataAnalysisController.ts
> +    const expensesGrouped = await Expense.findAll({
To have better type in this query you can do the query and usage below:

```
const expensesGrouped = await Expense.findAndCountAll({
      where: await buildDataAnalysisQuery(authenticatedUser, {
        startDate,
        endDate,
        departmentId
      }),
      attributes: ["currentStatus"],
      group: ["currentStatus"]
    });

    const groupedData = {
      PENDING: 0,
      APPROVED: 0,
      REJECTED: 0
    };

    expensesGrouped.count.forEach((c) => {
      const status = c.currentStatus as string;
      const count = c.count;

      switch (status) {
        case ExpenseStatusEnum.PENDING_APPROVAL:
        case ExpenseStatusEnum.PENDING_ADDITIONAL_INFO:
          groupedData.PENDING += count;
          break;
        case ExpenseStatusEnum.APPROVED:
          groupedData.APPROVED += count;
          break;
        case ExpenseStatusEnum.REJECTED:
          groupedData.REJECTED += count;
          break;
        case ExpenseStatusEnum.CANCELLED:
        default:
          break;
      }
    });
```

2025-01-11 02:48 UTC, gaschneider commented on server/src/controllers/dataAnalysisController.ts
> +    const expensesByMonth = await Expense.findAll({
For queries like this where you need to select an aggregate function, you should set the type properly after the query, casting to the structure returned in the dataValues, like:

```
const expensesByMonth = (await Expense.findAll({
      attributes: [
        [sequelize.fn("MONTHNAME", sequelize.col("date")), "month"],
        [sequelize.fn("SUM", sequelize.col("amount")), "amount"]
      ],
      where: {
        [Op.and]: [
          { currentStatus: ExpenseStatusEnum.APPROVED },
          await buildDataAnalysisQuery(authenticatedUser, {
            startDate,
            endDate,
            departmentId
          })
        ]
      },
      group: [
        sequelize.fn("MONTH", sequelize.col("date")),
        sequelize.fn("MONTHNAME", sequelize.col("date"))
      ],
      order: [[sequelize.fn("MONTH", sequelize.col("date")), "ASC"]]
    })) as unknown as { dataValues: { month: string; amount: number } }[];

    const responseData = expensesByMonth.map((expense) => ({
      month: expense.dataValues.month,
      amount: Number(expense.dataValues.amount)
    }));
```

2025-01-11 02:48 UTC, gaschneider commented on server/src/controllers/dataAnalysisController.ts
> +      const category = expense.get("category_name") || "Uncategorized"; // Nome da categoria
Instead of using `.get` you should directly use the `expense.category?.name` or `expense.currentStatus`, also you dont need to add category.name to the attributes since you are already including the category to the selection.

2025-01-11 02:48 UTC, gaschneider commented on server/src/controllers/departmentController.ts
> +      res.status(200).json([]);
Here should return an error because user wasn't found, instead of 200, probably 404 or 401

2025-01-11 02:48 UTC, gaschneider commented on server/src/helpers/dataAnalysisQueryHelper.ts
> +  if (departmentId && accessibleDepartmentIds.includes(departmentId)) {
You probably wanna check `expensesQueryHelper.ts` for this part, some issues were happening due to wrong conditions in here, I assume they are happening here too.

2025-01-11 02:48 UTC, gaschneider commented on server/src/index.ts
> +import session from "express-session";
unused

2025-01-16 02:11 UTC, magicblak commented
Addressed issue

2025-01-16 03:23 UTC, magicblak commented
Regarding chart colors, materialUI ^7.23.2 does not support implementing different colors in the same dataset. We may map out new releases to implement different colors, but for now we'll keep "Expenses per Status" and "Amount per Status ($ CAD)" in that way.

2025-01-18 01:48 UTC, gaschneider approved these changes
All issues seems to be resolved, approving this

2025-01-22 12:04 UTC, merged